apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  title: ${{ values.appName }}
  annotations:
    vault.io/secrets-path: ${{ values.secretsPath }}
    vault.io/secrets-engine: ${{ values.vaultSecretEngine }}
    github.com/project-slug: ${{ values.orgName }}/${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-label-selector: 'app=${{ values.appName }}'
    argocd/app-name: ${{ values.appName }}
    prometheus.io/rule: container_memory_usage_bytes{pod=~"${{ values.appName }}-.*"}|pod,rate(container_cpu_usage_seconds_total{pod=~"${{ values.appName }}-.*"}[5m])|pod
  tags:
    - spring-boot
    - java
    - maven
    - kubernetes
    - argocd
    - vault
spec: 
  type: service
  owner: user:guest
  lifecycle: experimental